substitutions:
  name: "ikesp-aq" #Sets the $name variable for our device. This will be used as the entity name in Home Assistant. Sensors will show as "$name sensorname", for example "$name Temperature" for the temperature sensor.
  friendly_name: "IKESP AQ"

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: True #This should be changed to false if the device is given a unique name. 
  platform: ESP8266
  board: d1_mini
  project:
    name: CalumDay.IKESP-AQ
    version: dev

wifi:
  ssid: !secret wifi_ssid #set this in ESPHome secrets, or else insert it here as a string
  password: !secret wifi_password #set this in ESPHome secrets, or else insert it here as a string
  ap:
    ssid: "${name}"
    password: !secret fallback_ap_password #set this in ESPHome secrets, or else insert it here as a string

captive_portal:

api:
#  encryption:
#    key: "XXXXXX" # Create a new device in ESPHome, and copy the key from that yaml to here, then uncomment this lineand the line above. This appears to be neccessary as dashboard_import doesnt appear to support this feature.

ota:
  - platform: esphome
#    password: "XXXX" # Create a new device in ESPHome, and copy the ota password from that yaml to here, then uncoment this line. This appears to be neccessary as dashboard_import doesnt appear to support this feature.

logger: # This section allows us to enable loggin of individual sensors in the ESPHome logs. By default we have disabled logging of sensor outputs to keep the log clean, but this can be useful for troubleshooting sensors if you encounter an issue.
  logs:
    sensor: none
    binary_sensor: none
    pm1006: none
    ccs811: none

# Adding uart for PM1006 sensor
uart:
  - rx_pin: D5
    baud_rate: 9600

# Turn on the onboard LED on the D1 mini when the PM1006 is taking a reading
binary_sensor:
  - platform: gpio
    name: $name Fan
    id: fan
    pin:
      number: D4
      inverted: true

#Enable I2C for the BME280 and CCS811 boards
i2c:
  sda: D1
  scl: D2
  scan: true
  id: bus_a

# Add the sensors to allow output to HASS
sensor:
# PM1006
  - platform: pm1006
    id: aq_sensor
    pm_2_5:
      name: $friendly_name pm2.5 #name the entity in HASS, using the $name variable set at the top of this file.

# CCS811
  - platform: ccs811
    eco2:
      name: $friendly_name CO² #name the entity in HASS, using the $name variable set at the top of this file.
      accuracy_decimals: 0
    tvoc:
      name: $friendly_name T-VOC #name the entity in HASS, using the $name variable set at the top of this file.
      accuracy_decimals: 0
    address: 0x5A
    update_interval: 10s #set the update interval for the sensor. 10s is the default.
    temperature: bme_temp
    humidity: bme_humi
    # baseline: 0x4AB7 #Set the baseline for the Sensor. Uncomment this line after following the calibration procedure from https://github.com/CalumDay/IKESPHome-AQ

# BME280
  - platform: bme280_i2c
    temperature:
      name: $friendly_name Temperature #name the entity in HASS, using the $name variable set at the top of this file.
      id: bme_temp
      oversampling: 4x
    humidity:
      name: $friendly_name Humidity #name the entity in HASS, using the $name variable set at the top of this file.
      id: bme_humi
      oversampling: 4x
    pressure:
      name:  $friendly_name Pressure #name the entity in HASS, using the $name variable set at the top of this file.
      id: bme_press
      oversampling: 4x
    iir_filter: 16x
    address: 0x76
    update_interval: 10s
